version: '3.8'

services:
  eureka-server:
    image: eureka-server
    container_name: eureka-server
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - backend

  configserver:
    build:
      context: ./configServer
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    env_file:
      - .env
    networks:
      - backend

  ecommercedb:
    image: mysql:8.0.28
    environment:
      MYSQL_USER: 'userauth'
      MYSQL_PASSWORD: 'Moderesta2001'
      MYSQL_ROOT_PASSWORD: 'Moderesta2001'
    ports:
      - "3307:3306"
    volumes:
      - ecommercedb-data:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend

  userauth-service:
    build:
      context: ./userauth
      dockerfile: Dockerfile
    ports:
      - "5000:8081"
    depends_on:
      - ecommercedb
      - configserver
    environment:
      SPRING_CLOUD_CONFIG_URI: http://configserver:8888
    networks:
      - backend


  product-service:
    build:
      context: ./product
      dockerfile: Dockerfile
    ports:
      - "5001:8082"
    volumes:
      - ./product/src:/app/src
      - ./product/target:/app/target
    depends_on:
      - ecommercedb
      - configserver
      - eureka-server
    environment:
      SPRING_CLOUD_CONFIG_URI: http://configserver:8888
    networks:
      - backend

  cart-service:
    image: ecommerce-cart-service:latest
    build:
      context: ./cart
      dockerfile: Dockerfile
    ports:
      - "5002:8083"
    volumes:
      - ./cart/src:/app/src
      - ./cart/target:/app/target
    depends_on:
      - ecommercedb
      - configserver
    environment:
      SPRING_CLOUD_CONFIG_URI: http://configserver:8888
    networks:
      - backend

  order-service:
    build:
      context: ./order
      dockerfile: Dockerfile
    ports:
      - "5003:8084"
    volumes:
      - ./order/src:/app/src
      - ./order/target:/app/target
    depends_on:
      - ecommercedb
    environment:
     SPRING_CLOUD_CONFIG_URI: http://configserver:8888
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  ecommercedb-data:
