CREATE DATABASE IF NOT EXISTS UserAuth;
CREATE DATABASE IF NOT EXISTS Product;
CREATE DATABASE IF NOT EXISTS Cart;
CREATE DATABASE IF NOT EXISTS Orderdb;

CREATE USER IF NOT EXISTS 'userauth'@'%' IDENTIFIED BY 'Moderesta2001';
GRANT ALL PRIVILEGES ON UserAuth.* TO 'userauth'@'%';
GRANT ALL PRIVILEGES ON Product.* TO 'userauth'@'%';
GRANT ALL PRIVILEGES ON Cart.* TO 'userauth'@'%';
GRANT ALL PRIVILEGES ON Orderdb.* TO 'userauth'@'%';
FLUSH PRIVILEGES;
